# -*- coding: utf-8 -*-
"""optimization dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYVqTI48Fz_-eI6nVCTPwdaopw558OqB
"""

import streamlit as st
import pandas as pd
import pulp
import numpy as np

# ---------------- Optimization Function ----------------
def optimize_supplier(df, nego_percent, total_demand, target_quality, target_delivery):
    df = df.copy()

    # Apply negotiation %
    df["EffectivePrice"] = df["UnitPrice"] * (1 - np.array(nego_percent) / 100)

    # Feasibility check
    if total_demand > df["MaxCapacity"].sum():
        return df.assign(
            OptimizedVolume=0,
            OptimizedSpend=0,
            Savings=0
        ), "Infeasible (Demand > Total Capacity)"

    # LP Model
    model = pulp.LpProblem("Supplier_Optimization", pulp.LpMinimize)

    volumes = {
        row.Supplier: pulp.LpVariable(
            f"vol_{row.Supplier}",
            lowBound=0,
            upBound=int(row.MaxCapacity),
            cat="Integer"
        )
        for _, row in df.iterrows()
    }

    # Objective: Minimize Cost
    model += pulp.lpSum(
        volumes[row.Supplier] * row.EffectivePrice
        for _, row in df.iterrows()
    )

    # Constraints
    model += pulp.lpSum(volumes[row.Supplier] for _, row in df.iterrows()) == int(total_demand)
    model += pulp.lpSum(volumes[row.Supplier] * row.Quality for _, row in df.iterrows()) >= target_quality * total_demand
    model += pulp.lpSum(volumes[row.Supplier] * row.Delivery for _, row in df.iterrows()) >= target_delivery * total_demand

    # Solve
    model.solve(pulp.PULP_CBC_CMD(msg=0))
    status = pulp.LpStatus[model.status]

    # Results
    if status == "Optimal":
        df["OptimizedVolume"] = [int(pulp.value(volumes[row.Supplier])) for _, row in df.iterrows()]
        df["OptimizedSpend"] = df["OptimizedVolume"] * df["EffectivePrice"]
        df["Savings"] = df["CurrentVolume"] * df["UnitPrice"] - df["OptimizedSpend"]
    else:
        df["OptimizedVolume"] = 0
        df["OptimizedSpend"] = 0
        df["Savings"] = 0

    return df, status

# ---------------- Streamlit UI ----------------
def main():
    st.title("Supplier Optimization Dashboard")

    # Base Data
    data = {
        "Supplier": ["S1", "S2"],
        "UnitPrice": [3.365, 2.830],
        "CurrentVolume": [1060527, 799717],  # used internally only
        "Quality": [0.95, 0.92],
        "Delivery": [0.93, 0.89],
        "MaxCapacity": [12000, 900]
    }

    df = pd.DataFrame(data)

    # User Inputs
    total_demand = st.number_input("Total Demand", value=18600, step=100)
    target_quality = st.number_input("Minimum Quality", value=0.8, step=0.05)
    target_delivery = st.number_input("Minimum Delivery", value=0.8, step=0.05)

    nego_s1 = st.slider("S1 Negotiation %", -20.0, 20.0, 0.0)
    nego_s2 = st.slider("S2 Negotiation %", -20.0, 20.0, 0.0)

    s1_cap = st.number_input("S1 Max Capacity", value=12000, step=100)
    s2_cap = st.number_input("S2 Max Capacity", value=900, step=100)

    df.loc[df["Supplier"] == "S1", "MaxCapacity"] = s1_cap
    df.loc[df["Supplier"] == "S2", "MaxCapacity"] = s2_cap

    # Run Optimization
    if st.button("Run Optimization"):
        nego_percent = [nego_s1, nego_s2]
        results, status = optimize_supplier(
            df, nego_percent, total_demand, target_quality, target_delivery
        )

        st.subheader("Optimization Results")
        st.write(f"Solver Status: **{status}**")

        # 🔥 REMOVE CurrentVolume FROM DISPLAY
        display_results = results[
            [
                "Supplier",
                "UnitPrice",
                "EffectivePrice",
                "Quality",
                "Delivery",
                "MaxCapacity",
                "OptimizedVolume",
                "OptimizedSpend",
                "Savings"
            ]
        ]

        st.dataframe(display_results)

        # KPIs
        if status == "Optimal":
            total_quality = (results["OptimizedVolume"] * results["Quality"]).sum() / total_demand
            total_delivery = (results["OptimizedVolume"] * results["Delivery"]).sum() / total_demand
            total_spend = results["OptimizedSpend"].sum()
            total_savings = results["Savings"].sum()

            st.metric("Achieved Quality", f"{total_quality:.2f}")
            st.metric("Achieved Delivery", f"{total_delivery:.2f}")
            st.metric("Total Spend", f"₹{total_spend:,.2f}")
            st.metric("Total Savings", f"₹{total_savings:,.2f}")

# ---------------- Run App ----------------
if __name__ == "__main__":
    main()