# -*- coding: utf-8 -*-
"""optimization and simulation dashboard .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYVqTI48Fz_-eI6nVCTPwdaopw558OqB
"""

import streamlit as st
import pandas as pd
import pulp
import numpy as np

# ---------------- Optimization Function ----------------
def optimize_supplier(df, nego_percent, total_demand, target_quality, target_delivery):
    df = df.copy()

    # Effective negotiated price
    df["EffectivePrice"] = df["UnitPrice"] * (1 - np.array(nego_percent) / 100)

    # Feasibility check
    if total_demand > df["MaxCapacity"].sum():
        return df.assign(
            OptimizedVolume=0,
            OptimizedSpend=0,
            NegotiationSavings=0
        ), "Infeasible (Demand > Total Capacity)"

    # LP Model
    model = pulp.LpProblem("Supplier_Optimization", pulp.LpMinimize)

    volumes = {
        row.Supplier: pulp.LpVariable(
            f"vol_{row.Supplier}",
            lowBound=0,
            upBound=int(row.MaxCapacity),
            cat="Integer"
        )
        for _, row in df.iterrows()
    }

    # Objective: Minimize total cost
    model += pulp.lpSum(
        volumes[row.Supplier] * row.EffectivePrice
        for _, row in df.iterrows()
    )

    # Constraints
    model += pulp.lpSum(volumes[row.Supplier] for _, row in df.iterrows()) == int(total_demand)
    model += pulp.lpSum(volumes[row.Supplier] * row.Quality for _, row in df.iterrows()) >= target_quality * total_demand
    model += pulp.lpSum(volumes[row.Supplier] * row.Delivery for _, row in df.iterrows()) >= target_delivery * total_demand

    # Solve
    model.solve(pulp.PULP_CBC_CMD(msg=0))
    status = pulp.LpStatus[model.status]

    if status == "Optimal":
        df["OptimizedVolume"] = [int(pulp.value(volumes[row.Supplier])) for _, row in df.iterrows()]
        df["OptimizedSpend"] = df["OptimizedVolume"] * df["EffectivePrice"]
        df["BaselineSpend"] = df["OptimizedVolume"] * df["UnitPrice"]
        df["NegotiationSavings"] = df["BaselineSpend"] - df["OptimizedSpend"]
    else:
        df["OptimizedVolume"] = 0
        df["OptimizedSpend"] = 0
        df["NegotiationSavings"] = 0

    return df, status

# ---------------- Streamlit UI ----------------
def main():
    st.title("Supplier Price Negotiation & Optimization Simulator")

    st.markdown("### 🔧 Supplier Inputs")

    # Editable base data
    data = {
        "Supplier": ["S1", "S2"],
        "UnitPrice": [
            st.number_input("S1 Unit Price", value=3.365, step=0.01),
            st.number_input("S2 Unit Price", value=2.830, step=0.01)
        ],
        "Quality": [0.95, 0.92],
        "Delivery": [0.93, 0.89],
        "MaxCapacity": [
            st.number_input("S1 Max Capacity", value=12000, step=100),
            st.number_input("S2 Max Capacity", value=900, step=100)
        ]
    }

    df = pd.DataFrame(data)

    st.markdown("### 📊 Demand & Constraints")

    total_demand = st.number_input("Total Demand", value=18600, step=100)
    target_quality = st.number_input("Minimum Quality", value=0.8, step=0.05)
    target_delivery = st.number_input("Minimum Delivery", value=0.8, step=0.05)

    st.markdown("### 💰 Negotiation Scenario (%)")

    nego_s1 = st.slider("S1 Negotiation %", -20.0, 20.0, 0.0)
    nego_s2 = st.slider("S2 Negotiation %", -20.0, 20.0, 0.0)

    if st.button("Run Simulation & Optimization"):
        nego_percent = [nego_s1, nego_s2]

        results, status = optimize_supplier(
            df,
            nego_percent,
            total_demand,
            target_quality,
            target_delivery
        )

        st.subheader("📌 Optimization Results")
        st.write(f"Solver Status: **{status}**")

        display_results = results[
            [
                "Supplier",
                "UnitPrice",
                "EffectivePrice",
                "OptimizedVolume",
                "OptimizedSpend",
                "NegotiationSavings"
            ]
        ]

        st.dataframe(display_results)

        if status == "Optimal":
            total_baseline = results["BaselineSpend"].sum()
            total_optimized = results["OptimizedSpend"].sum()
            total_savings = results["NegotiationSavings"].sum()

            st.markdown("### 📈 Simulation Summary")

            st.metric("Baseline Spend (Before Negotiation)", f"₹{total_baseline:,.2f}")
            st.metric("Optimized Spend (After Negotiation)", f"₹{total_optimized:,.2f}")
            st.metric("Total Negotiation Savings", f"₹{total_savings:,.2f}")

# ---------------- Run App ----------------
if __name__ == "__main__":
    main()